---
http:
  port: 8080
logging:
  debug: stdout
  verbose: stdout
  error: stderr
paths:
  assets: "./static"
  staticpages: "./static-content"
  mdpages: "./md-content"
  feedback: "/tmp/"
  generators: "./etc/generators.yaml"
  data: "/tmp/"
features:
  blog: true
  app: true
  contact: true