---
http:
  port: 8088
logging:
  debug: stdout
  verbose: stdout
  error: stderr
paths:
  assets: "./static"
  staticpages: "./static-content"
  mdpages: "./md-content"
  feedback: "/tmp/"
  generators: "./etc/generators.yaml"
  data: "/tmp/"
features:
  blog: true
  app: true
  contact: true
  twitter: true
  github: true
statictexts:
  copyrightline: "© 2017 @aschmidt75, AGPLv3/dual licensed. Blog content is CC BY-SA 4.0"