{{define `main`}}
<div id="main" class="no-container">
    <div class="row">
        <div class="col s12">
        {{ if .Message }}
            <div class="card red darken-2">
                <div class="card-content white-text">
                {{ .Message }}
                </div>
            </div>
        {{ else }}
            <div class="row" id="gen">
                <div class="col s9">
                    <h4>Generate!</h4>
                    <div>
                        <p>
                            Congrats, all items necessary for generating your device code are present!<br>
                            You can review your settings here. If you need modifications, you may jump back
                            to previous pages.
                        </p>
                    </div>
                    <div id="gen_review" class=" z-depth-1">
                        <div class="row">
                            <div class="col s12">
                                <ul class="tabs">
                                    <li class="tab col s2"><a class="active tc-maincolor-text" href="#gen_review_thing">Thing</a></li>
                                    <li class="tab col s3"><a class="tc-maincolor-text" href="#gen_review_framework">Framework</a></li>
                                    <li class="tab col s3"><a class="tc-maincolor-text" href="#gen_review_properties">Properties</a></li>
                                    <li class="tab col s2"><a class="tc-maincolor-text" href="#gen_review_actions">Actions</a></li>
                                    <li class="tab col s2"><a class="tc-maincolor-text" href="#gen_review_events">Events</a></li>
                                </ul>
                            </div>
                            <div id="gen_review_thing" class="col s12">
                            </div>
                            <div id="gen_review_framework" class="col s12">
                            </div>
                            <div id="gen_review_properties" class="col s12">
                            </div>
                            <div id="gen_review_actions" class="col s12">
                            </div>
                            <div id="gen_review_events" class="col s12">
                            </div>

                        </div>
                    </div>

                    </section>
                    <div id="gen_accept col s6">
                        <div class="card grey lighten-2">
                            <div class="card-content">
                                <p>
                                The code which is generated by the framework module you selected is
                                intended for personal and educational use ONLY. It is provided as a
                                <a target="tc-ext" href="https://creativecommons.org/publicdomain/zero/1.0/legalcode">CC0 1.0 Universal public domain dedication</a>.
                                </p>
                                <p>
                                    This code is offered as-is and without any warranty; without even the
                                    implied warranty of merchantability or fitness for a particular purpose.
                                </p>
                            </div>
                            <div class="card-action ">
                                <p>Please tick the checkbox below if you agree with the conditions above.</p>

                                <input id="gen_accept_cb" type="checkbox" class="filled-in tc-maincolor" />
                                <label for="gen_accept_cb" class="teal-text">
                                    <span>I understand, let's roll.</span>
                                </label>
                            </div>
                        </div>
                        <div id="gen_go_div" class="col s12">

                        </div>
                    </div>
                    </section>
                </div>
                <div class="col s2 offset-s1 hide-on-med-and-down">
                    <p>
                    <ul class="section table-of-contents">
                        <li>Create</li>
                        <li>Framework{{ if .TocInfo.framework }}&nbsp;(<span>{{ index .TocInfo "framework" }}</span>){{end}}</li>
                        <li>Properties{{ if .TocInfo.num_properties }}&nbsp;(<span>{{ index .TocInfo "num_properties" }}</span>){{end}}</li>
                        <li>Actions{{ if .TocInfo.num_actions }}&nbsp;(<span>{{ index .TocInfo "num_actions" }}</span>){{end}}</li>
                        <li>Events{{ if .TocInfo.num_events }}&nbsp;(<span>{{ index .TocInfo "num_events" }}</span>){{end}}</li>
                        <li><strong class="tc-maincolor-text">Generate!</strong></li>
                    </ul>
                    </p>
                </div>
            </div>

        {{ end }}
        </div>
    </div>


    <!-- hidden, tools -->
    <div id="tpl_gen_go_div" class="hide">
        <form id="gen_go_f" name="gen_go_f" method="POST" action="/app/{{ .ThingId }}/generate">
            <input type="hidden" value="" id="gen_go_token" name="token">
            <input type="hidden" value="{{.ThingId}}" id="gen_go_id" name="id">
            <button id="gen_go" class="btn tc-maincolor waves-effect waves-light col s5 right" type="submit" name="gen_go">
                Generate!
                <i class="material-icons right">build</i>
            </button>
        </form>
    </div>

</div>

{{end}}